version: '3.7'

volumes:
  bundle:
  node_modules:

services:
  app:
    build:
      context: .
    command: sh -c '(bundle check || bundle install) && yarn && bundle exec puma && bin/vite dev'
    restart: always
    volumes:
      - .:/app:delegated
      - node_modules:/app/node_modules
      - bundle:/bundle
    ports:
      - '3000:3000'
      - '3036:3036'
    environment:
      BUNDLE_PATH: /bundle
