version: '3.7'

volumes:
  bundle:
  node_modules:

services:
  app:
    build:
      context: .
    command: sh -c '(bundle check || bundle install) && yarn && bundle exec puma'
    restart: always
    volumes:
      - .:/app:delegated
      - node_modules:/app/node_modules
      - bundle:/bundle
    ports:
      - '3000:3000'
    environment:
      BUNDLE_PATH: /bundle
      VITE_RUBY_HOST: vite
    depends_on:
      - vite

  vite:
    build:
      context: .
    command: sh -c '(bundle check || bundle install) && yarn && ./bin/vite dev'
    volumes:
      - .:/app:delegated
      - bundle:/bundle
      - node_modules:/app/node_modules
    ports:
      - '3036:3036'
    environment:
      BUNDLE_PATH: /bundle
      RAILS_ENV: development
      VITE_RUBY_HOST: 0.0.0.0
